
server:
  port: 8080

spring:
  datasource:
    name:
    username: root
    password: 123456
    url: jdbc:mysql://localhost/mytest?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

